eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:1111/eureka/

spring:
  cloud:
    config:
      uri: http://localhost:8888